### ISSUE TITLE
Disable markdown in frontmatter

### ISSUE THREAD

**Issue by cyotek** [mike-ward/Markdown-Edit#237]
Although I'd be happier if the preview pane didn't show yaml front matter at all, I see from #131 that this is currently by design. I would like to propose that if you can detect the presence of yaml you don't treat it as markdown.

For example, I have the current block of yaml at the top of a MD file

``` yaml
---
title: Acknowledgements
layout: topic.html
output: acknowledgements.html
seealsocategories:
- d34d2d99-c5a3-4aae-b08f-be3e93296074
---
```

Which renders the yaml list as markdown which is a touch distracting:

![image](https://cloud.githubusercontent.com/assets/859574/23558037/1028677a-002a-11e7-9760-42fa299afcba.png)

It would be nice if MDE wouldn't treat the yaml block as markdown. Bonus points if it was possible to control the style of the yaml (e.g. I would format it with a monospace font and a different coloured background to make it very clear it's not part of the main document)
